spring:
  application:
    name: goo

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://3.93.236.79 :3306/goo?serverTimezone=Asia/Seoul
    username: 'root'
    password: ''

  jpa:
    #    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  security:
    oauth2:
      client:
        registration:
          kakao:
            #            client_id: ${kakao_client_id}
            client_id: "94d54435b2c08988febb12b2d5d13854"
            #            client_secret: ${kakao_client_secret}
            client_secret: "Dxzdky48hPSfiv8ArBsz8bGAc2FgQdku"
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect_uri: "http://3.93.236.79:8080/login/oauth2/code/kakao"
            #            redirect_logout_uri: ${kakao_redirect_logout_uri}
            redirect_logout_uri: "http://3.93.236.79:8080"
            scope: "profile_nickname, account_email"
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id




